# docker-compose.yml

services:
  flask-backend:
    build: ./flask-backend  # Build from Dockerfile in the flask-backend folder
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network
    platform: linux/amd64  # Optional for M1

  react-frontend:
    build: ./react-frontend  # Build from Dockerfile in the react-frontend folder
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network
    platform: linux/amd64  # Optional for M1

networks:
  app-network:
    driver: bridge
